In [38]:
import torch
import math


def self_attention(Q, K, V):
    # b t d
    #prod = Q.bmm(K.permute(0, 2, 1))
    prod = torch.einsum("btd, bsd -> bts", Q, K)
    scaled_prod = prod/torch.sqrt(torch.tensor(Q.shape[-1]))
    softmaxed_prod = torch.nn.functional.softmax(scaled_prod, dim=-1)
    print(softmaxed_prod.shape)
    print(softmaxed_prod)
    return softmaxed_prod.bmm(V)


x = torch.rand([2, 3, 4])
self_attention(x, x, x)
self_attention(x, x, x).shape

torch.Size([2, 3, 3])
tensor([[[0.4189, 0.2613, 0.3197],
         [0.3650, 0.3149, 0.3201],
         [0.3279, 0.2350, 0.4370]],

        [[0.3488, 0.2995, 0.3518],
         [0.2417, 0.3859, 0.3724],
         [0.2332, 0.3058, 0.4610]]])
torch.Size([2, 3, 3])
tensor([[[0.4189, 0.2613, 0.3197],
         [0.3650, 0.3149, 0.3201],
         [0.3279, 0.2350, 0.4370]],

        [[0.3488, 0.2995, 0.3518],
         [0.2417, 0.3859, 0.3724],
         [0.2332, 0.3058, 0.4610]]])


torch.Size([2, 3, 4])

In [26]:
torch.nn.functional.softmax(torch.rand([2,3]))

/var/folders/yp/nh9d_4t54_j3lb4kljncwfj40000gp/T/ipykernel_91734/2143963450.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  torch.nn.functional.softmax(torch.rand([2,3]))


tensor([[0.2549, 0.3325, 0.4125],
        [0.4198, 0.2815, 0.2987]])

In [20]:
import math
math.sqrt(9)
torch.sqrt(torch.tensor(9))

tensor(3.)

In [4]:
torch.rand([2,3,4]).T.shape

torch.Size([4, 3, 2])